### PR TITLE
Move chart to helm-chart directory

### PR DESCRIPTION
**Pull request by manics**
This means we can use the cryptnono directory as a Python package

Requires the latest release of chartpress

### CODE REVIEW

**Comment by yuvipanda** [comment]
Wheeee!

**Comment by GeorgianaElena** [comment]
For some reason, I cannot find any of the published chart at their regular location.

For example the latest chart version https://yuvipanda.github.io/cryptnono/cryptnono-0.3.1-0.dev.git.127.hbd4f166.tgz is not there, and this is true for the previous ones as well. I believe it is related to this PR, maybe something that should have been updated with the new path but hasn't?

**Comment by manics** [comment]
It's present in the gh-pages branch on GitHub:
- https://github.com/cryptnono/cryptnono/tree/gh-pages
- https://github.com/cryptnono/cryptnono/commit/9aa0f4ee71138df7723c283c249b15725e6e18c9 is the update corresponding to this PR

**Comment by manics** [comment]
Oh, looks like this repo was moved from yuvipanda to a new org https://github.com/cryptnono/

**Comment by GeorgianaElena** [comment]
Aaaaah, right! Thank you very much @manics! Wouldn't spot the ownership change in 100years without your help!

**Comment by yuvipanda** [comment]
Ah, I moved it for this blog post (https://github.com/2i2c-org/2i2c-org.github.io/pull/205) but that broke publishing. I'll fix that today.

**Pull request merged**
